weathersite/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    # path("login/", views.login, name="login"),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterUserView.as_view(), name="register"),
]

weathersite/weather/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.WeatherHomeView.as_view(), name="index"),
    path("weather/", views.ShowLocationView.as_view(), name="search"),
    path("location/add/", views.AddLocationView.as_view(), name="add_location"),
    path(
        "location/delete/<int:pk>/",
        views.DeleteWeatherCardView.as_view(),
        name="delete_location",
    ),
]

weathersite/weathersite/urls.py
from django.contrib import admin
from django.urls import path, include

from weather.views import page_not_found

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("weather.urls")),
    path("users/", include("users.urls", namespace="users")),
]

handler404 = page_not_found

weathersite/users/models.py
# from django.db import models

# Create your models here.

weathersite/weather/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.


class Location(models.Model):
    name = models.CharField(max_length=100)  # type: ignore[var-annotated]
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # type: ignore[var-annotated]
    latitude = models.DecimalField(max_digits=10, decimal_places=7)  # type: ignore[var-annotated]
    longitude = models.DecimalField(max_digits=10, decimal_places=7)  # type: ignore[var-annotated]

    def __str__(self) -> str:
        return self.name

weathersite/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control me-2 "})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control me-2"})
    )


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control me-2 "})
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control me-2"}),
        label="Password",
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control me-2"}),
        label="Confirm Password",
    )

weathersite/users/views.py
import logging

from django import forms
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import LoginUserForm, RegisterUserForm
from users.utils import RedirectAuthenticatedUserMixin

# Create your views here.
logger = logging.getLogger("users")


class LoginUserView(RedirectAuthenticatedUserMixin, LoginView):
    form_class = LoginUserForm
    template_name = "users/login.html"
    extra_context = {"title": "Authorization."}


class RegisterUserView(RedirectAuthenticatedUserMixin, CreateView):
    form_class = RegisterUserForm
    template_name = "users/register.html"
    success_url = reverse_lazy("index")
    extra_context = {"title": "Registration."}

    def form_valid(self, form: forms.Form) -> HttpResponse:
        response = super().form_valid(form)
        login(self.request, self.object)
        return response

weathersite/weather/views.py
import logging
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, View, ListView, DeleteView

from .models import Location
from .utils import WeatherSearchMixin, WeatherDataMixin

# Create your views here.

logger = logging.getLogger("weather")


class WeatherHomeView(LoginRequiredMixin, WeatherDataMixin, ListView):
    model = Location
    template_name = "weather/index.html"
    context_object_name = "locations_with_weather"
    paginate_by = 8

    def get_queryset(self) -> QuerySet[Location]:
        locations = Location.objects.filter(user=self.request.user)
        return self._add_weather_data(locations)  # type: ignore

    def _add_weather_data(self, locations: QuerySet[Location]) -> list[dict[str, Any]]:
        weather_data, error = self.handle_weather_request(locations)
        if error:
            self.error = error
        return weather_data

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if hasattr(self, "error"):
            context["error"] = self.error
        elif not context["locations_with_weather"]:
            context["info"] = "You don't have any saved locations yet."
        return context


class ShowLocationView(LoginRequiredMixin, WeatherSearchMixin, TemplateView):
    template_name = "weather/locations.html"
    extra_context = {"title": "Search."}

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get("city", "").strip()
        logger.debug("Query: %s", query)

        if not query:
            logger.warning("No city specified")
            context["info"] = "Please enter a city name"
            return context

        locations, error = self.handle_search(query)
        if error:
            context["error"] = error
        else:
            context.update({"locations": locations, "query": query})
        return context


class DeleteWeatherCardView(DeleteView):
    model = Location
    success_url = reverse_lazy("index")

    def get_queryset(self) -> QuerySet[Location]:
        logger.warning("User %s deleted location", self.request.user)
        return super().get_queryset().filter(user=self.request.user)


class AddLocationView(LoginRequiredMixin, View):
    def post(self, request: HttpRequest) -> HttpResponse:
        Location.objects.get_or_create(
            user=request.user,
            name=request.POST.get("name"),
            latitude=request.POST.get("latitude"),
            longitude=request.POST.get("longitude"),
        )
        logger.info(
            "User %s added location: %s", request.user, request.POST.get("name")
        )

        return redirect("index")


def page_not_found(request: HttpRequest, exception: Exception) -> HttpResponse:
    logger.warning("404 Not Found: %s", request.path)
    return render(request, "weather/not_found.html")

weathersite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'weather/images/favicon.svg' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link type="text/css" href="{% static 'weather/css/style.css' %}" rel="stylesheet"/>
    <title>WeatherApp. {{ title }}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg weather-gradient sticky-top shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'weather/images/sun.svg' %}" alt="AppLogo">
            WeatherApp
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% block navbar_content %}
        {% endblock %}

    </div>
</nav>

<!-- Core part -->
<div class="main-content" style="min-height: calc(100vh - 120px); padding-bottom: 40px;">
    {% block content %}
    {% endblock %}
</div>


<!-- Footer -->
<nav class="navbar weather-gradient fixed-bottom ">
    <div class="container-fluid justify-content-center">
        <div class="d-flex">
            <a class="nav-link active mx-2" aria-current="page" href="https://t.me/Dmitry_D321" target="_blank">
                <img src="{% static 'weather/images/telegram.svg' %}" alt="Telegram">
            </a>
            <a class="nav-link active mx-2" aria-current="page" href="https://github.com/Dmitry-DVal/WeatherApp" target="_blank">
                <img src="{% static 'weather/images/github.svg' %}" alt="GitHub">
            </a>
        </div>
    </div>
</nav>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
        crossorigin="anonymous"></script>
</body>
</html>

weathersite/users/templates/users/includes/nav_users.html
{% load static %}

<div class="collapse navbar-collapse justify-content-right" id="navbarSupportedContent">
    <div class="me-auto"></div>

    <ul class="navbar-nav">
        <li class="nav-item me-3">
            <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Login
                <img src="{% static 'users/images/login.svg' %}" alt="" class="ms-1">
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'users:register' %}">Registration
                <img src="{% static 'users/images/pen.svg' %}" alt="">
            </a>
        </li>
    </ul>

</div>

weathersite/users/templates/users/login.html
{% extends 'base.html' %}

{% block navbar_content %}
    {% include 'users/includes/nav_users.html' %}
{% endblock %}

{% block content %}

    <div class="container col-md-4 col-md-offset-4">
        <h2 class="mb-4 mt-4 fw-light" style="color: #002855">Authorization to WeatherApp.</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p>
                <button class="btn btn-outline-primary col-md-4 col-md-offset-4" type="submit">Sign in</button>
            </p>
        </form>
    </div>
{% endblock %}

weathersite/users/templates/users/register.html
{% extends 'base.html' %}

{% block navbar_content %}
    {% include 'users/includes/nav_users.html' %}
{% endblock %}

{% block content %}

    <div class="container col-md-4 col-md-offset-4">
        <h2 class="mb-4 mt-4 fw-light" style="color: #002855">Registration to WeatherApp.</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p>
                <button class="btn btn-outline-primary col-md-4 col-md-offset-4" type="submit">Register</button>
            </p>
        </form>
    </div>
{% endblock %}

weathersite/weather/templates/weather/includes/location_card.html
{% load static %}

<div class="col-sm-6 col-md-4 col-lg-3">
    <div class="card h-100 p-0 shadow">
        <div class="card-body d-flex flex-column">

            <div class="d-flex justify-content-between align-items-start mb-3">
                <div class="flex-shrink-0 me-0 ml-0 pl-0">
                    <img src="{{ location.icon_url }}" alt="Weather icon" width="96" height="96">
                </div>

                <div class="w-100">
                    <div class="d-flex justify-content-between align-items-start">
                        <h2 class="mb-0" style="color: #002855; font-size: 2rem;">
                            {{ location.main.temp|floatformat:0 }}℃
                        </h2>

                        <form id="delete-form-{{ location.db_id }}" action="{% url 'delete_location' location.db_id %}"
                              method="POST">
                            {% csrf_token %}
                            <a href="#" class="text-decoration-none remove-btn"
                               onclick="document.getElementById('delete-form-{{ location.db_id }}').submit()">
                                <img src="{% static 'weather/images/x-lg.svg' %}" alt="Remove" width="20">
                            </a>
                        </form>

                    </div>

                    <div class="mt-1">
                        <small class="text-muted">
                            Ощущается как {{ location.main.feels_like|floatformat:0 }}℃
                        </small>
                    </div>
                    <div class="mt-1" style="font-size: 1.1rem;">
                        {{ location.timezone }}
                    </div>
                </div>
            </div>

            <h3 class="mt-2 mb-3" style="color: #002855; font-size: 1.5rem;">
                {{ location.name }}, {{ location.sys.country }}
                <img src="{% static 'weather/images/flags/' %}{{ location.sys.country|lower }}.svg" alt="flag"
                     width="50" class="flag">
            </h3>

            <div class="mb-3 text-capitalize">
                {{ location.weather.0.description }}
            </div>
            <div class="d-flex align-items-center mt-0">
                <div class="d-flex align-items-center">
                    <img src="{% static 'weather/images/wind.svg' %}" alt="Wind" width="20" class="me-2">
                    {{ location.wind.speed }} m/s
                </div>
                <div class="d-flex align-items-center">
                    <img src="{% static 'weather/images/droplet.svg' %}" alt="Humidity" width="20" class="me-2">
                    {{ location.main.humidity }}%
                </div>
            </div>

        </div>
    </div>
</div>

weathersite/weather/templates/weather/includes/nav.html
{% load static %}

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link disabled">{{ user.username }}
                <img src="{% static 'weather/images/settings.svg' %}" alt="">
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"
               onclick="document.getElementById('logout-form').submit()">
                Logout
                <img src="{% static 'weather/images/logout.svg' %}" alt="" class="ms-1">
            </a>
            <form id="logout-form" method="post" action="{% url 'users:logout' %}" style="display: none;">
                {% csrf_token %}
            </form>
        </li>
    </ul>
    <form class="d-flex" role="search"  method="GET" action="{% url 'search' %}">
        <input class="form-control me-2" type="search" placeholder="Searching" aria-label="Searching" name="city">
        <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>
</div>

weathersite/weather/templates/weather/includes/warning_error.html
{% load static %}

{% if info %}
    <div class="container alert alert-primary">
        <img src="{% static 'weather/images/attention.svg' %}" alt="attention">
        {{ info }}
    </div>
{% endif %}

{% if error %}
    <div class="container alert alert-danger">
        <img src="{% static 'weather/images/attention.svg' %}" alt="attention">
        {{ error }}
    </div>
{% endif %}

weathersite/weather/templates/weather/index.html
{% extends 'base.html' %}
{% load static %}

{% block navbar_content %}
    {% include 'weather/includes/nav.html' %}
{% endblock %}

{% block content %}
    <h1 class="mb-2 mt-2 text-center fw-light" style="color: #002855">Weather Dashboard</h1>

    {% include 'weather/includes/warning_error.html' %}



    {% if locations_with_weather %}
        <div class="container">
            <div class="row g-4">
                {% for location in locations_with_weather %}
                    {% include 'weather/includes/location_card.html' %}

                {% endfor %}
            </div>
        </div>
    {% endif %}



    {% block navigation %}
        {% if page_obj.has_other_pages %}

            <nav aria-label="Навигации по страницам">
                <ul class="pagination d-flex justify-content-center mt-4 ">

                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                               aria-label="Предыдущая">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for p in paginator.page_range %}
                        {% if p == page_obj.number %}
                            <li class="page-item page-link weather-navbar">{{ p }}</li>
                        {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:+2 %}
                            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Следующая">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}

                </ul>
            </nav>

        {% endif %}
    {% endblock %}

{% endblock %}

weathersite/weather/templates/weather/locations.html
{% extends 'base.html' %}
{% load static %}

{% block navbar_content %}
    {% include 'weather/includes/nav.html' %}
{% endblock %}

{% block content %}
    <h1 class="mb-4 mt-4 text-center fw-light" style="color: #002855">Found locations on
        request: {{ query|lower|capfirst }}</h1>

    {% include 'weather/includes/warning_error.html' %}

    <div class="container">
        <div class="row g-5">
            {% if locations %}
                {% for location in locations %}

                    <div class="col-sm-6 col-md-4 col-lg-3">
                        <div class="card h-100 p-3 shadow-sm">
                            <div class="card-body d-flex flex-column">
                                <div>
                                    <img class="flag m-3 mt-0"
                                         src="{% static 'weather/images/flags/' %}{{ location.country|lower }}.svg"
                                         alt="flag" width="75">
                                </div>
                                <h4 class="card-title mb-3 px-3" style="color: #002855">
                                    {{ location.name }}, {{ location.country }}

                                </h4>
                                <div class="my-2 px-3">
                                    <div>Lat: {{ location.lat|floatformat:6 }}</div>
                                    <div>Lon: {{ location.lon|floatformat:6 }}</div>
                                </div>
                                <div class="mt-auto">
                                    <div class="px-3">
                                        <form action="{% url 'add_location' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name="name" value="{{ location.name }}"></input>
                                            <input type="hidden" name="latitude" value="{{ location.lat }}"></input>
                                            <input type="hidden" name="longitude" value="{{ location.lon }}"></input>
                                            <button class="btn btn-outline-primary w-100 mt-3">
                                                Add
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock %}

weathersite/weather/templates/weather/not_found.html
{% extends 'base.html' %}

{% block navbar_content %}
    {% include 'weather/includes/nav.html' %}
{% endblock %}

{% block content %}
    <h1 class="mb-2 mt-2 text-center fw-light" style="color: #002855">
        404. Sorry, we don't know what you are looking for.
    </h1>
{% endblock %}